#!/usr/bin/env python3
"""
Regenerate the port and board choices in copier.yaml from mpbuild.

mpbuild is the authority on which ports it can build in a container, so the
question's choices are derived from it rather than hand-maintained. The result
is written into copier.yaml between marker comments so copier itself stays
offline: questions are answered before anything is cloned or installed.

The resolution deliberately goes through `uv run --with mpbuild` rather than
whatever mpbuild happens to be importable. A checked-in generated list has to
be reproducible, and a developer with a local mpbuild checkout would otherwise
produce a different list from CI. The version used is recorded in the
generated block so a disagreement is diagnosable.

    python3 tools/sync_ports.py           # rewrite copier.yaml
    python3 tools/sync_ports.py --check   # exit 1 if out of date (used by CI)
"""

import argparse
import os
import re
import shutil
import subprocess
import tempfile
import sys
from pathlib import Path

COPIER_YAML = Path(__file__).resolve().parent.parent / "copier.yaml"

BEGIN = "  # BEGIN ports generated by tools/sync_mpbuild.py\n"
END = "  # END ports generated by tools/sync_mpbuild.py\n"

BOARDS_BEGIN = "    # BEGIN boards generated by tools/sync_mpbuild.py\n"
BOARDS_END = "    # END boards generated by tools/sync_mpbuild.py\n"

MICROPYTHON_URL = "https://github.com/micropython/micropython.git"

# Ports mpbuild can build that this template has nothing to offer. The
# template generates firmware for a board, so ports that build a host binary
# or have no board definitions are excluded; unix is kept because it is the
# test target and is useful on its own.
EXCLUDED = {"webassembly", "windows"}

_BOOTSTRAP_ENV = "MPY_TEMPLATE_SYNC_BOOTSTRAPPED"


def ports():
    from mpbuild.build import BUILD_CONTAINERS

    return sorted(set(BUILD_CONTAINERS) - EXCLUDED)


def boards_by_port(mpy_dir, port_names):
    """Map each port to the boards mpbuild finds for it."""
    from mpbuild import board_database

    database = board_database(Path(mpy_dir))
    by_port = {name: [] for name in port_names}
    for name, board in sorted(database.boards.items()):
        if board.port.name in by_port:
            by_port[board.port.name].append(name)
    return {port: names for port, names in by_port.items() if names}


def micropython_checkout(supplied):
    """A MicroPython tree to enumerate boards from."""
    if supplied:
        return Path(supplied), describe(supplied)
    tmp = Path(tempfile.mkdtemp(prefix="sync_mpbuild_"))
    dest = tmp / "micropython"
    print(f"Cloning MicroPython into {dest}")
    subprocess.run(
        ["git", "clone", "--quiet", "--depth", "1", MICROPYTHON_URL, str(dest)],
        check=True,
    )
    return dest, describe(dest)


def describe(mpy_dir):
    result = subprocess.run(
        ["git", "-C", str(mpy_dir), "rev-parse", "--short", "HEAD"],
        capture_output=True, text=True, check=False,
    )
    return result.stdout.strip() or "unknown"


def mpbuild_version():
    from importlib.metadata import version

    return version("mpbuild")


def ensure_mpbuild():
    """Re-exec under a freshly resolved mpbuild, ignoring any local install."""
    if os.environ.get(_BOOTSTRAP_ENV):
        try:
            import mpbuild  # noqa: F401
        except ImportError:
            sys.exit("mpbuild unavailable after bootstrap")
        return
    uv = shutil.which("uv")
    if not uv:
        sys.exit("uv not found; install it from https://docs.astral.sh/uv/")
    os.environ[_BOOTSTRAP_ENV] = "1"
    os.execvp(uv, [uv, "run", "--quiet", "--no-project", "--with", "mpbuild",
                   "python", str(Path(__file__).resolve()), *sys.argv[1:]])


def render_ports(port_names, version):
    lines = [BEGIN, f"  # mpbuild {version}\n"]
    lines += [f"    - {name}\n" for name in port_names]
    lines.append(END)
    return "".join(lines)


def render_boards(by_port, version, mpy_ref):
    lines = [BOARDS_BEGIN, f"    # mpbuild {version}, MicroPython {mpy_ref}\n"]
    for port, names in by_port.items():
        lines.append(f"    {port}:\n")
        lines += [f"      - {name}\n" for name in names]
    lines.append(BOARDS_END)
    return "".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the port choices are out of date")
    parser.add_argument("--micropython", metavar="PATH",
                        help="MicroPython checkout to enumerate boards from "
                             "(default: shallow clone of master)")
    args = parser.parse_args()

    ensure_mpbuild()

    current = COPIER_YAML.read_text()
    for marker in (BEGIN, END, BOARDS_BEGIN, BOARDS_END):
        if marker not in current:
            sys.exit(f"Marker not found in {COPIER_YAML}: {marker.strip()}")

    version = mpbuild_version()
    port_names = ports()

    updated = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END),
                     render_ports(port_names, version), current, flags=re.S)

    if args.check:
        # Only the port list is checked. It comes from mpbuild's own table, so
        # it is fixed by the mpbuild version, whereas the board lists follow
        # MicroPython and would turn this red every time a board lands
        # upstream. A board list that has fallen behind costs a choice in the
        # prompt, and initial_setup.py validates the answer against the real
        # tree either way.
        if updated != current:
            print("Port choices are out of date; run tools/sync_mpbuild.py")
            subprocess.run(["diff", "-u", "-", str(COPIER_YAML)],
                           input=updated, text=True, check=False)
            sys.exit(1)
        print("Port choices are up to date")
        return

    mpy_dir, mpy_ref = micropython_checkout(args.micropython)
    by_port = boards_by_port(mpy_dir, port_names)
    updated = re.sub(re.escape(BOARDS_BEGIN) + r".*?" + re.escape(BOARDS_END),
                     render_boards(by_port, version, mpy_ref), updated, flags=re.S)

    if updated != current:
        COPIER_YAML.write_text(updated)
        total = sum(len(names) for names in by_port.values())
        print(f"Updated {COPIER_YAML}: {len(port_names)} ports, {total} boards")
    else:
        print("Already up to date")


if __name__ == "__main__":
    main()
