#!/usr/bin/env python3
"""
Regenerate the target_port choices in copier.yaml from mpbuild.

mpbuild is the authority on which ports it can build in a container, so the
question's choices are derived from it rather than hand-maintained. The result
is written into copier.yaml between marker comments so copier itself stays
offline: questions are answered before anything is cloned or installed.

The resolution deliberately goes through `uv run --with mpbuild` rather than
whatever mpbuild happens to be importable. A checked-in generated list has to
be reproducible, and a developer with a local mpbuild checkout would otherwise
produce a different list from CI. The version used is recorded in the
generated block so a disagreement is diagnosable.

    python3 tools/sync_ports.py           # rewrite copier.yaml
    python3 tools/sync_ports.py --check   # exit 1 if out of date (used by CI)
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

COPIER_YAML = Path(__file__).resolve().parent.parent / "copier.yaml"

BEGIN = "  # BEGIN generated by tools/sync_ports.py\n"
END = "  # END generated by tools/sync_ports.py\n"

# Ports mpbuild can build that this template has nothing to offer. The
# template generates firmware for a board, so ports that build a host binary
# or have no board definitions are excluded; unix is kept because it is the
# test target and is useful on its own.
EXCLUDED = {"webassembly", "windows"}

_BOOTSTRAP_ENV = "MPY_TEMPLATE_SYNC_BOOTSTRAPPED"


def ports():
    from mpbuild.build import BUILD_CONTAINERS

    return sorted(set(BUILD_CONTAINERS) - EXCLUDED)


def mpbuild_version():
    from importlib.metadata import version

    return version("mpbuild")


def ensure_mpbuild():
    """Re-exec under a freshly resolved mpbuild, ignoring any local install."""
    if os.environ.get(_BOOTSTRAP_ENV):
        try:
            import mpbuild  # noqa: F401
        except ImportError:
            sys.exit("mpbuild unavailable after bootstrap")
        return
    uv = shutil.which("uv")
    if not uv:
        sys.exit("uv not found; install it from https://docs.astral.sh/uv/")
    os.environ[_BOOTSTRAP_ENV] = "1"
    os.execvp(uv, [uv, "run", "--quiet", "--no-project", "--with", "mpbuild",
                   "python", str(Path(__file__).resolve()), *sys.argv[1:]])


def render(port_names, version):
    lines = [BEGIN, f"  # mpbuild {version}\n"]
    lines += [f"    - {name}\n" for name in port_names]
    lines.append(END)
    return "".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if copier.yaml is out of date")
    args = parser.parse_args()

    ensure_mpbuild()

    current = COPIER_YAML.read_text()
    if BEGIN not in current or END not in current:
        sys.exit(f"Markers not found in {COPIER_YAML}")

    block = render(ports(), mpbuild_version())
    updated = re.sub(
        re.escape(BEGIN) + r".*?" + re.escape(END), block, current, flags=re.S
    )

    if args.check:
        if updated != current:
            print("copier.yaml port choices are out of date; run tools/sync_ports.py")
            subprocess.run(["diff", "-u", "-", str(COPIER_YAML)],
                           input=updated, text=True, check=False)
            sys.exit(1)
        print("copier.yaml port choices are up to date")
        return

    if updated != current:
        COPIER_YAML.write_text(updated)
        print(f"Updated {COPIER_YAML}")
    else:
        print("Already up to date")


if __name__ == "__main__":
    main()
